repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    - id: trailing-whitespace
-   repo: https://github.com/team5499/pre-commit-hooks
    rev: v0.3.2
    hooks:
    -   id: ktlint-wrapper
        args: [--color, --format, --relative, --verbose]
    -   id: detekt-wrapper
        args: [--config .detekt-config.yml]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.11.1  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@^4.19.1
        -   eslint-config-airbnb-base@13.1.0
        -   eslint-plugin-import@2.14.0
